name: "KidsLock Manager"
version: "1.0.1"
slug: "kidslock-manager"
description: "Beheer schermtijd voor Android TV"
url: "https://github.com/svdveer/kidslock-manager"
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
init: false
services:
  - mqtt: need
options:
  tvs: []
schema:
  tvs:
    - name: str
      ip: str
      daily_limit: int
      bedtime: str
      no_limit_mode: bool
ingress: true
ingress_port: 8000
panel_icon: mdi:lock-clock
