name: "KidsLock Manager"
version: "1.7.2.2"
slug: "kidslock_manager"
description: "De mooie Legacy-versie met FastAPI, weekschema en realtime MQTT"
arch:
  - aarch64
  - amd64
  - armv7
ingress: true
ingress_port: 8000
panel_icon: "mdi:lock-smart"
panel_title: "KidsLock"