name: "KidsLock Manager"
version: "2.3.1"
slug: "kidslock-manager"
description: "v2.3.1 - MQTT controls for KidsLock"
url: "https://github.com/svdveer/kidslock-repository"
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: auto
ingress: true
ingress_port: 8000
panel_icon: "mdi:shield-lock"
mqtt: true
network:
  8000/tcp: 8000
privileged:
  - NET_ADMIN
options:
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
schema:
  mqtt_host: str?
  mqtt_port: int?
  mqtt_user: str?
  mqtt_password: str?