name: "KidsLock Manager"
version: "1.7.2.5"
slug: "kidslock_manager"
description: "De volledige KidsLock met weekschema, onbeperkt-modus en realtime MQTT"
arch:
  - aarch64
  - amd64
  - armv7
init: false
ingress: true
ingress_port: 8000
panel_icon: "mdi:lock-smart"
panel_title: "KidsLock"